server:
  port: 8081
spring:
  application:
    name: config-server
  profiles:
    active: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dirknowitzki123/mall
          search-paths:
          username: 413150745@qq.com
          password: aini18716374124

#注册中心配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/