############# 开发环境配置 #################
server:
  port: 8079
spring:
  application:
    name: dirk-prod-service
  profiles:
    active: dev
    #active: ${env:dev}

eureka:
  client:
    # 开发测试; 开启健康检查(需要spring-boot-starter-actuator依赖)
    # 客户端发送心跳包时会带上自己的健康信息
    #healthcheck:
    #  enabled: true
    #service-url:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      #defaultZone: http://${spring.cloud.client.hostname}:8761/eureka/

ribbon:
  eureka:
    enabled: true
#ribbon:
#  #请求处理的超时时间 单位:毫秒 2个小时 = 2*60*60*1000 = 7200000毫秒 30分钟=30*60*1000
#  ReadTimeout: 4000
#  ConnectTimeout: 3000
#  MaxAutoRetries: 1